package cloner

import (
	"bytes"
	"fmt"
	"strings"
	"text/template"
)

// FieldSpec describes a single field for code generation.
type FieldSpec struct {
	// Name is the Go field name (e.g., "ID", "Email").
	Name string

	// Type is the Go type string (e.g., "string", "[]string",
	// "map[string]string", "*Address").
	Type string
}

// GenerateOptions configures the code generation output.
type GenerateOptions struct {
	// PackageName is the Go package for the generated file.
	PackageName string

	// TypeName is the struct name to generate a cloner for.
	TypeName string

	// Fields is the list of fields in the struct.
	Fields []FieldSpec
}

// Generate produces Go source code for a type-specific Clone function.
// The generated function does not use reflection and is safe for concurrent use.
func Generate(opts GenerateOptions) ([]byte, error) {
	if opts.PackageName == "" {
		return nil, fmt.Errorf("codegen: PackageName is required")
	}
	if opts.TypeName == "" {
		return nil, fmt.Errorf("codegen: TypeName is required")
	}

	data := templateData{
		Package:  opts.PackageName,
		TypeName: opts.TypeName,
		Fields:   make([]fieldData, len(opts.Fields)),
	}

	for i, f := range opts.Fields {
		data.Fields[i] = fieldData{
			Name:     f.Name,
			Type:     f.Type,
			CopyExpr: copyExpression(f),
		}
	}

	var buf bytes.Buffer
	tmpl, err := template.New("cloner").Parse(clonerTemplate)
	if err != nil {
		return nil, fmt.Errorf("codegen: template parse: %w", err)
	}
	if err := tmpl.Execute(&buf, data); err != nil {
		return nil, fmt.Errorf("codegen: template execute: %w", err)
	}

	return buf.Bytes(), nil
}

type templateData struct {
	Package  string
	TypeName string
	Fields   []fieldData
}

type fieldData struct {
	Name     string
	Type     string
	CopyExpr string
}

// copyExpression generates the Go expression to deep-copy a field.
func copyExpression(f FieldSpec) string {
	switch {
	case strings.HasPrefix(f.Type, "[]"):
		return fmt.Sprintf(`func() %s {
		if src.%s == nil { return nil }
		cp := make(%s, len(src.%s))
		copy(cp, src.%s)
		return cp
	}()`, f.Type, f.Name, f.Type, f.Name, f.Name)

	case strings.HasPrefix(f.Type, "map["):
		return fmt.Sprintf(`func() %s {
		if src.%s == nil { return nil }
		cp := make(%s, len(src.%s))
		for k, v := range src.%s { cp[k] = v }
		return cp
	}()`, f.Type, f.Name, f.Type, f.Name, f.Name)

	case strings.HasPrefix(f.Type, "*"):
		return fmt.Sprintf(`func() %s {
		if src.%s == nil { return nil }
		v := *src.%s
		return &v
	}()`, f.Type, f.Name, f.Name)

	default:
		// Value type — direct copy.
		return fmt.Sprintf("src.%s", f.Name)
	}
}

const clonerTemplate = `// Code generated by go-audit codegen; DO NOT EDIT.
package {{.Package}}

import (
	"context"
	"fmt"
)

// {{.TypeName}}Cloner implements ClonerPort for {{.TypeName}} using direct field access.
type {{.TypeName}}Cloner struct{}

// Clone returns an independent deep copy of entity.
// The entity must be *{{.TypeName}}; returns a *{{.TypeName}}.
func (c *{{.TypeName}}Cloner) Clone(_ context.Context, entity any) (any, error) {
	src, ok := entity.(*{{.TypeName}})
	if !ok {
		return nil, fmt.Errorf("{{.TypeName}}Cloner: expected *{{.TypeName}}, got %T", entity)
	}
	dst := &{{.TypeName}}{
{{- range .Fields}}
		{{.Name}}: {{.CopyExpr}},
{{- end}}
	}
	return dst, nil
}
`
